version: '3'

services:
  #rabbit mq
  rabbitmq:
    image: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
  # #redis
  redis-server: 
    restart: always
    image: redis:6.0-alpine
    volumes:
      - ./server/redis-volume:/data
    ports:
      - '6379:6379'
    # expose:
    #   - 6379
  #frontend
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  
  # backend
  server:
    build: ./server
    environment:
      MONGO_URI: mongodb://mongo:27017/user_management
      REDIS_URL: redis://redis-server:6379
      RMQ_URL: amqp://rabbitmq:5672
      SECRET_JWT: NishantSecretKey
      MA_KEY: 49uriefv7l0i1obekollxhpu
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - redis-server
      - rabbitmq
  

  #mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./server/mongo-volume:/data/db
      - ./server/mongo-volume-configdb:/data/configdb
    ports:
      - '27017:27017'
  #nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    ports: 
      - 80:80
    depends_on:
      - server       
    restart: always

volumes:
  mongo: {}
